spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:53306/caat?serverTimezone=UTC&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: test

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true